#!/usr/bin/env python3
import argparse
from websocket import create_connection
import json
import random
import string
import re
import pandas as pd
from datetime import datetime
from time import sleep
import sqlite3
import yaml

config = yaml.safe_load(open("quantfin.cfg.yml")) 

for ticker in tickerlist:
  

parser = argparse.ArgumentParser()
parser.add_argument("a")
args = parser.parse_args()
print(args.echo)
